replicaCount: 1

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/go-web-app
  pullPolicy: IfNotPresent
  tag: 613160b

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: dev.prasanna-aws.com
      paths:
        - path: /
          pathType: Prefix

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
