replicaCount: 3

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/go-web-app
  pullPolicy: IfNotPresent
  tag: a3e3804

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: go-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific

