replicaCount: 1

global:
  awsAccountId: "837717008195"
  region: ap-south-1
  ecrRepository: endtoend   # <-- must match the ECR repo your CI pushes to

image:
  tag: "b03431e"            # <-- CI image tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: staging.prasanna-aws.cloud
      paths:
        - path: /
          pathType: Prefix
