replicaCount: 1

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/go-web-app
  pullPolicy: IfNotPresent
  # CI pipeline will update this automatically
  tag: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: PLACEHOLDER_HOST
      paths:
        - path: /
          pathType: Prefix
